---
# Copyright 2017 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Google Cloud Builder CI configuration
#
steps:
  #
  # Cancel the previous build for the same branch
  #
  - name: gcr.io/cloud-builders/gcloud-slim:latest
    id: cancelot
    entrypoint: bash
    args: [./ci/cancelot.sh, $BUILD_ID, $PROJECT_ID]

substitutions:
  _CACHE_BUCKET: agones-build-cache
  _HTMLTEST_CACHE_KEY: htmltest-0.10.1
  _CPP_SDK_BUILD_CACHE_KEY: cpp-sdk-build
  _CPP_SDK_CONFORMANCE_CACHE_KEY: cpp-sdk-conformance
  _RUST_SDK_BUILD_CACHE_KEY: rust-sdk-build
  _REGISTRY: us-docker.pkg.dev/${PROJECT_ID}/ci
tags: [ci, 'commit-${COMMIT_SHA}']
timeout: 18000s  # 5h: 3h (e2e-wait-to-become-leader) + 1.5h (e2e timeout) + 0.5h (everything else)
queueTtl: 259200s  # 72h
images:
  - ${_REGISTRY}/agones-controller
  - ${_REGISTRY}/agones-extensions
  - ${_REGISTRY}/agones-sdk
  - ${_REGISTRY}/agones-ping
  - ${_REGISTRY}/agones-allocator
logsBucket: gs://agones-build-logs
options:
  machineType: E2_HIGHCPU_32
  dynamic_substitutions: true
