// Copyright 2024 Google LLC All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	autoscalingv1 "agones.dev/agones/pkg/apis/autoscaling/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FleetAutoscalerLister helps list FleetAutoscalers.
// All objects returned here must be treated as read-only.
type FleetAutoscalerLister interface {
	// List lists all FleetAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1.FleetAutoscaler, err error)
	// FleetAutoscalers returns an object that can list and get FleetAutoscalers.
	FleetAutoscalers(namespace string) FleetAutoscalerNamespaceLister
	FleetAutoscalerListerExpansion
}

// fleetAutoscalerLister implements the FleetAutoscalerLister interface.
type fleetAutoscalerLister struct {
	listers.ResourceIndexer[*autoscalingv1.FleetAutoscaler]
}

// NewFleetAutoscalerLister returns a new FleetAutoscalerLister.
func NewFleetAutoscalerLister(indexer cache.Indexer) FleetAutoscalerLister {
	return &fleetAutoscalerLister{listers.New[*autoscalingv1.FleetAutoscaler](indexer, autoscalingv1.Resource("fleetautoscaler"))}
}

// FleetAutoscalers returns an object that can list and get FleetAutoscalers.
func (s *fleetAutoscalerLister) FleetAutoscalers(namespace string) FleetAutoscalerNamespaceLister {
	return fleetAutoscalerNamespaceLister{listers.NewNamespaced[*autoscalingv1.FleetAutoscaler](s.ResourceIndexer, namespace)}
}

// FleetAutoscalerNamespaceLister helps list and get FleetAutoscalers.
// All objects returned here must be treated as read-only.
type FleetAutoscalerNamespaceLister interface {
	// List lists all FleetAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1.FleetAutoscaler, err error)
	// Get retrieves the FleetAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingv1.FleetAutoscaler, error)
	FleetAutoscalerNamespaceListerExpansion
}

// fleetAutoscalerNamespaceLister implements the FleetAutoscalerNamespaceLister
// interface.
type fleetAutoscalerNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingv1.FleetAutoscaler]
}
