[module]
_merge = "deep"
# work around https://github.com/golang/go/issues/37397
[[module.mounts]]
  source = "assets/bootstrap/scss/_vendor"
  target = "assets/vendor/bootstrap/scss/vendor"
# mount asserts directory
[[module.mounts]]
  source = "assets"
  target = "assets"
# mount i18n directory
[[module.mounts]]
  source = "i18n"
  target = "i18n"
# mount layouts directory
[[module.mounts]]
  source = "layouts"
  target = "layouts"
# mount static directory
[[module.mounts]]
  source = "static"
  target = "static"
# Dependencies are brought in as modules
# and mount points are declared
[[module.imports]]
  path = "github.com/twbs/bootstrap"
  disable = false
  ignoreConfig = true
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/bootstrap/scss"
[[module.imports.mounts]]
  source = "dist/js"
  target = "assets/vendor/bootstrap/dist/js"
[[module.imports]]
  path = "github.com/FortAwesome/Font-Awesome"
  disable = false
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/Font-Awesome/scss"
[[module.imports.mounts]]
  source = "webfonts"
  target = "static/webfonts"
