# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
publish = "userguide/public"
command = "npm run docs-install && npm run build:preview"

[build.environment]
GO_VERSION = "1.19.5"
HUGO_THEME = "repo"

[context.production]
command = "npm run docs-install && npm run build:production"
