---
# Copyright 2024 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# [Stage:Dev]
# [FeatureFlag:ScheduledAutoscaler]
# Example of a FleetAutoscaler - this is used to scale a Fleet based on a schedule.
#

#
# For a full reference and details: https://agones.dev/site/docs/reference/fleetautoscaler/
#
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: chain-fleet-autoscaler
spec:
  policy:
    # Chain based policy for autoscaling.
    type: Chain
    chain:
      # UID of chain entry. Optional.
      - uid: "weekday"
        type: Schedule  # Schedule based condition.
        schedule:
          between:
            # The policy becomes eligible for application starting on
            # Feb 20, 2024 at 4:04 PM EST. Optional.
            start: "2024-02-20T16:04:04-05:00"
            # The policy becomes ineligible for application on
            # Feb 23, 2024 at 4:04 PM EST. Optional.
            end: "2024-02-23T16:04:04-05:00"
          activePeriod:
            # Timezone to be used for the startCron field.
            # Optional.
            timezone: "America/New_York"
            # Start applying the bufferSize everyday at 1:00  AM EST.
            # (Only eligible starting on Feb 20, 2024 at 4:04 PM.) Optional.
            startCron: "0 1 * * 0"
            # Only apply the bufferSize for this 5 hours
            # Optional.
            duration: "5h"
        # Policy to be applied when the condition is met. Required.
        policy:
          type: Buffer
          buffer:
            bufferSize: 50
            minReplicas: 100
            maxReplicas: 2000
      # UID of chain entry. Optional.
      - uid: "weekend"
        type: Schedule
        schedule:
          between:
            # The policy becomes eligible for application starting on
            # Feb 24, 2024 at 4:05 PM EST.
            # Optional.
            start: "2024-02-24T16:04:05-05:00"
            # The policy becomes ineligible for application starting on
            # Feb 26, 2024 at 4:05 PM EST.
            # Optional.
            end: "2024-02-26T16:04:05-05:00"
          activePeriod:
            # Timezone to be used for the schedule.
            timezone: "America/New_York"
            # Start applying the bufferSize everyday at 1:00  AM EST.
            # (Only eligible starting on Feb 24, 2024 at 4:05 PM EST)
            # Optional.
            startCron: "0 1 * * 0"
            # Only apply the bufferSize for this 7 hours
            # Optional.
            duration: "7h"
        # Policy to be applied when the condition is met. Required.
        policy:
          type: Counter
          counter:
            key: rooms
            bufferSize: 10
            minCapacity: 500
            maxCapacity: 1000
      # UID of chain entry.
      - uid: "default"
        # Policy will always be applied when no other policy is applicable. Required.
        policy:
          type: Buffer
          buffer:
            bufferSize: 5
            minReplicas: 100
            maxReplicas: 2000
