// Copyright 2023 Google LLC All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.
// GENERATED CODE -- DO NOT EDIT!

// Original file comments:
// Copyright 2020 Google LLC All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
'use strict';
var alpha_pb = require('./alpha_pb.js');
var google_api_annotations_pb = require('./google/api/annotations_pb.js');
var google_api_client_pb = require('./google/api/client_pb.js');
var google_api_field_behavior_pb = require('./google/api/field_behavior_pb.js');
var google_api_resource_pb = require('./google/api/resource_pb.js');
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js');
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var protoc$gen$openapiv2_options_annotations_pb = require('./protoc-gen-openapiv2/options/annotations_pb.js');

function serialize_agones_dev_sdk_alpha_AddListValueRequest(arg) {
  if (!(arg instanceof alpha_pb.AddListValueRequest)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.AddListValueRequest');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_AddListValueRequest(buffer_arg) {
  return alpha_pb.AddListValueRequest.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_Bool(arg) {
  if (!(arg instanceof alpha_pb.Bool)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.Bool');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_Bool(buffer_arg) {
  return alpha_pb.Bool.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_Count(arg) {
  if (!(arg instanceof alpha_pb.Count)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.Count');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_Count(buffer_arg) {
  return alpha_pb.Count.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_Counter(arg) {
  if (!(arg instanceof alpha_pb.Counter)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.Counter');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_Counter(buffer_arg) {
  return alpha_pb.Counter.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_Empty(arg) {
  if (!(arg instanceof alpha_pb.Empty)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.Empty');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_Empty(buffer_arg) {
  return alpha_pb.Empty.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_GetCounterRequest(arg) {
  if (!(arg instanceof alpha_pb.GetCounterRequest)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.GetCounterRequest');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_GetCounterRequest(buffer_arg) {
  return alpha_pb.GetCounterRequest.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_GetListRequest(arg) {
  if (!(arg instanceof alpha_pb.GetListRequest)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.GetListRequest');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_GetListRequest(buffer_arg) {
  return alpha_pb.GetListRequest.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_List(arg) {
  if (!(arg instanceof alpha_pb.List)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.List');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_List(buffer_arg) {
  return alpha_pb.List.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_PlayerID(arg) {
  if (!(arg instanceof alpha_pb.PlayerID)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.PlayerID');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_PlayerID(buffer_arg) {
  return alpha_pb.PlayerID.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_PlayerIDList(arg) {
  if (!(arg instanceof alpha_pb.PlayerIDList)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.PlayerIDList');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_PlayerIDList(buffer_arg) {
  return alpha_pb.PlayerIDList.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_RemoveListValueRequest(arg) {
  if (!(arg instanceof alpha_pb.RemoveListValueRequest)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.RemoveListValueRequest');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_RemoveListValueRequest(buffer_arg) {
  return alpha_pb.RemoveListValueRequest.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_UpdateCounterRequest(arg) {
  if (!(arg instanceof alpha_pb.UpdateCounterRequest)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.UpdateCounterRequest');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_UpdateCounterRequest(buffer_arg) {
  return alpha_pb.UpdateCounterRequest.deserializeBinary(new Uint8Array(buffer_arg));
}

function serialize_agones_dev_sdk_alpha_UpdateListRequest(arg) {
  if (!(arg instanceof alpha_pb.UpdateListRequest)) {
    throw new Error('Expected argument of type agones.dev.sdk.alpha.UpdateListRequest');
  }
  return Buffer.from(arg.serializeBinary());
}

function deserialize_agones_dev_sdk_alpha_UpdateListRequest(buffer_arg) {
  return alpha_pb.UpdateListRequest.deserializeBinary(new Uint8Array(buffer_arg));
}


// SDK service to be used in the GameServer SDK to the Pod Sidecar.
var SDKService = exports['agones.dev.sdk.alpha.SDK'] = {
  // PlayerConnect increases the SDK’s stored player count by one, and appends this playerID to GameServer.Status.Players.IDs.
//
// GameServer.Status.Players.Count and GameServer.Status.Players.IDs are then set to update the player count and id list a second from now,
// unless there is already an update pending, in which case the update joins that batch operation.
//
// PlayerConnect returns true and adds the playerID to the list of playerIDs if this playerID was not already in the
// list of connected playerIDs.
//
// If the playerID exists within the list of connected playerIDs, PlayerConnect will return false, and the list of
// connected playerIDs will be left unchanged.
//
// An error will be returned if the playerID was not already in the list of connected playerIDs but the player capacity for
// the server has been reached. The playerID will not be added to the list of playerIDs.
//
// Warning: Do not use this method if you are manually managing GameServer.Status.Players.IDs and GameServer.Status.Players.Count
// through the Kubernetes API, as indeterminate results will occur.
playerConnect: {
    path: '/agones.dev.sdk.alpha.SDK/PlayerConnect',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.PlayerID,
    responseType: alpha_pb.Bool,
    requestSerialize: serialize_agones_dev_sdk_alpha_PlayerID,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_PlayerID,
    responseSerialize: serialize_agones_dev_sdk_alpha_Bool,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_Bool,
  },
  // Decreases the SDK’s stored player count by one, and removes the playerID from GameServer.Status.Players.IDs.
//
// GameServer.Status.Players.Count and GameServer.Status.Players.IDs are then set to update the player count and id list a second from now,
// unless there is already an update pending, in which case the update joins that batch operation.
//
// PlayerDisconnect will return true and remove the supplied playerID from the list of connected playerIDs if the
// playerID value exists within the list.
//
// If the playerID was not in the list of connected playerIDs, the call will return false, and the connected playerID list
// will be left unchanged.
//
// Warning: Do not use this method if you are manually managing GameServer.status.players.IDs and GameServer.status.players.Count
// through the Kubernetes API, as indeterminate results will occur.
playerDisconnect: {
    path: '/agones.dev.sdk.alpha.SDK/PlayerDisconnect',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.PlayerID,
    responseType: alpha_pb.Bool,
    requestSerialize: serialize_agones_dev_sdk_alpha_PlayerID,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_PlayerID,
    responseSerialize: serialize_agones_dev_sdk_alpha_Bool,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_Bool,
  },
  // Update the GameServer.Status.Players.Capacity value with a new capacity.
setPlayerCapacity: {
    path: '/agones.dev.sdk.alpha.SDK/SetPlayerCapacity',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.Count,
    responseType: alpha_pb.Empty,
    requestSerialize: serialize_agones_dev_sdk_alpha_Count,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_Count,
    responseSerialize: serialize_agones_dev_sdk_alpha_Empty,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_Empty,
  },
  // Retrieves the current player capacity. This is always accurate from what has been set through this SDK,
// even if the value has yet to be updated on the GameServer status resource.
//
// If GameServer.Status.Players.Capacity is set manually through the Kubernetes API, use SDK.GameServer() or SDK.WatchGameServer() instead to view this value.
getPlayerCapacity: {
    path: '/agones.dev.sdk.alpha.SDK/GetPlayerCapacity',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.Empty,
    responseType: alpha_pb.Count,
    requestSerialize: serialize_agones_dev_sdk_alpha_Empty,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_Empty,
    responseSerialize: serialize_agones_dev_sdk_alpha_Count,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_Count,
  },
  // Retrieves the current player count. This is always accurate from what has been set through this SDK,
// even if the value has yet to be updated on the GameServer status resource.
//
// If GameServer.Status.Players.Count is set manually through the Kubernetes API, use SDK.GameServer() or SDK.WatchGameServer() instead to view this value.
getPlayerCount: {
    path: '/agones.dev.sdk.alpha.SDK/GetPlayerCount',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.Empty,
    responseType: alpha_pb.Count,
    requestSerialize: serialize_agones_dev_sdk_alpha_Empty,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_Empty,
    responseSerialize: serialize_agones_dev_sdk_alpha_Count,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_Count,
  },
  // Returns if the playerID is currently connected to the GameServer. This is always accurate from what has been set through this SDK,
// even if the value has yet to be updated on the GameServer status resource.
//
// If GameServer.Status.Players.IDs is set manually through the Kubernetes API, use SDK.GameServer() or SDK.WatchGameServer() instead to determine connected status.
isPlayerConnected: {
    path: '/agones.dev.sdk.alpha.SDK/IsPlayerConnected',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.PlayerID,
    responseType: alpha_pb.Bool,
    requestSerialize: serialize_agones_dev_sdk_alpha_PlayerID,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_PlayerID,
    responseSerialize: serialize_agones_dev_sdk_alpha_Bool,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_Bool,
  },
  // Returns the list of the currently connected player ids. This is always accurate from what has been set through this SDK,
// even if the value has yet to be updated on the GameServer status resource.
//
// If GameServer.Status.Players.IDs is set manually through the Kubernetes API, use SDK.GameServer() or SDK.WatchGameServer() instead to view this value.
getConnectedPlayers: {
    path: '/agones.dev.sdk.alpha.SDK/GetConnectedPlayers',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.Empty,
    responseType: alpha_pb.PlayerIDList,
    requestSerialize: serialize_agones_dev_sdk_alpha_Empty,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_Empty,
    responseSerialize: serialize_agones_dev_sdk_alpha_PlayerIDList,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_PlayerIDList,
  },
  // Gets a Counter. Returns NOT_FOUND if the Counter does not exist.
getCounter: {
    path: '/agones.dev.sdk.alpha.SDK/GetCounter',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.GetCounterRequest,
    responseType: alpha_pb.Counter,
    requestSerialize: serialize_agones_dev_sdk_alpha_GetCounterRequest,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_GetCounterRequest,
    responseSerialize: serialize_agones_dev_sdk_alpha_Counter,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_Counter,
  },
  // UpdateCounter returns the updated Counter. Returns NOT_FOUND if the Counter does not exist (name cannot be updated).
// Returns OUT_OF_RANGE if the Count is out of range [0,Capacity].
updateCounter: {
    path: '/agones.dev.sdk.alpha.SDK/UpdateCounter',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.UpdateCounterRequest,
    responseType: alpha_pb.Counter,
    requestSerialize: serialize_agones_dev_sdk_alpha_UpdateCounterRequest,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_UpdateCounterRequest,
    responseSerialize: serialize_agones_dev_sdk_alpha_Counter,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_Counter,
  },
  // Gets a List. Returns NOT_FOUND if the List does not exist.
getList: {
    path: '/agones.dev.sdk.alpha.SDK/GetList',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.GetListRequest,
    responseType: alpha_pb.List,
    requestSerialize: serialize_agones_dev_sdk_alpha_GetListRequest,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_GetListRequest,
    responseSerialize: serialize_agones_dev_sdk_alpha_List,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_List,
  },
  // UpdateList returns the updated List. Returns NOT_FOUND if the List does not exist (name cannot be updated).
// **THIS WILL OVERWRITE ALL EXISTING LIST.VALUES WITH ANY REQUEST LIST.VALUES**
// Use AddListValue() or RemoveListValue() for modifying the List.Values field.
// Returns INVALID_ARGUMENT if the field mask path(s) are not field(s) of the List.
// If a field mask path(s) is specified, but the value is not set in the request List object,
// then the default value for the variable will be set (i.e. 0 for "capacity", empty list for "values").
updateList: {
    path: '/agones.dev.sdk.alpha.SDK/UpdateList',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.UpdateListRequest,
    responseType: alpha_pb.List,
    requestSerialize: serialize_agones_dev_sdk_alpha_UpdateListRequest,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_UpdateListRequest,
    responseSerialize: serialize_agones_dev_sdk_alpha_List,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_List,
  },
  // Adds a value to a List and returns updated List. Returns NOT_FOUND if the List does not exist.
// Returns ALREADY_EXISTS if the value is already in the List.
// Returns OUT_OF_RANGE if the List is already at Capacity.
addListValue: {
    path: '/agones.dev.sdk.alpha.SDK/AddListValue',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.AddListValueRequest,
    responseType: alpha_pb.List,
    requestSerialize: serialize_agones_dev_sdk_alpha_AddListValueRequest,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_AddListValueRequest,
    responseSerialize: serialize_agones_dev_sdk_alpha_List,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_List,
  },
  // Removes a value from a List and returns updated List. Returns NOT_FOUND if the List does not exist.
// Returns NOT_FOUND if the value is not in the List.
removeListValue: {
    path: '/agones.dev.sdk.alpha.SDK/RemoveListValue',
    requestStream: false,
    responseStream: false,
    requestType: alpha_pb.RemoveListValueRequest,
    responseType: alpha_pb.List,
    requestSerialize: serialize_agones_dev_sdk_alpha_RemoveListValueRequest,
    requestDeserialize: deserialize_agones_dev_sdk_alpha_RemoveListValueRequest,
    responseSerialize: serialize_agones_dev_sdk_alpha_List,
    responseDeserialize: deserialize_agones_dev_sdk_alpha_List,
  },
};

